# Generated by Django 5.2 on 2025-04-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('patr_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('deleted', models.BooleanField(default=False, verbose_name='Отметка об удалении записи')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('modify_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего изменения записи')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_users', to=settings.AUTH_USER_MODEL, verbose_name='Автор последнего изменения записи')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа документа')),
                ('deleted', models.BooleanField(default=False, verbose_name='Отметка об удалении записи')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('modify_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего изменения записи')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_types', to=settings.AUTH_USER_MODEL, verbose_name='Автор создания записи')),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_document_types', to=settings.AUTH_USER_MODEL, verbose_name='Автор последнего изменения записи')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные документов в формате JSON')),
                ('deleted', models.BooleanField(default=False, verbose_name='Отметка об удалении записи')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('modify_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего изменения записи')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Автор создания записи')),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Автор последнего изменения записи')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='personal_account.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='GenderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('deleted', models.BooleanField(default=False, verbose_name='Отметка об удалении записи')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('modify_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего изменения записи')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_genders', to=settings.AUTH_USER_MODEL, verbose_name='Автор создания записи')),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_genders', to=settings.AUTH_USER_MODEL, verbose_name='Автор последнего изменения записи')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Гендеры',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='gender_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='personal_account.gendertype', verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование типа')),
                ('deleted', models.BooleanField(default=False, verbose_name='Отметка об удалении записи')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('modify_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего изменения записи')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_types', to=settings.AUTH_USER_MODEL, verbose_name='Автор создания записи')),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_user_types', to=settings.AUTH_USER_MODEL, verbose_name='Автор последнего изменения записи')),
            ],
            options={
                'verbose_name': 'Тип пользователя',
                'verbose_name_plural': 'Типы пользователей',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='personal_account.usertype', verbose_name='Тип пользователя'),
        ),
    ]
