# Generated by Django 5.2 on 2025-04-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
