# Generated by Django 5.2 on 2025-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0003_users_is_active_users_is_staff'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('user', 'type'), name='unique_document_type_per_user'),
        ),
    ]
